export const mockProperties = [
  {
    id: 1,
    title: "Luxurious Oceanfront Estate",
    price: 12500000,
    bedrooms: 5,
    bathrooms: 5.5,
    squareFootage: 6500,
    yearBuilt: 2020,
    propertyType: "Single Family",
    status: "For Sale",
    location: "Kailua-Kona, HI",
    description: "Stunning oceanfront estate with panoramic views",
    images: ["/mock/property1.jpg"],
  },
  {
    id: 2,
    title: "Modern Beach Villa",
    price: 8750000,
    bedrooms: 4,
    bathrooms: 4,
    squareFootage: 4200,
    yearBuilt: 2019,
    propertyType: "Single Family",  // Changed from Villa
    status: "For Sale",
    location: "Wailea, HI",
    description: "Contemporary villa steps from the beach",
    images: ["/mock/property1.jpg"],
  },
  {
    id: 3,
    title: "Mountain View Retreat",
    price: 5900000,
    bedrooms: 3,
    bathrooms: 3.5,
    squareFootage: 3800,
    yearBuilt: 2018,
    propertyType: "Single Family",
    status: "For Sale",
    location: "Princeville, HI",
    description: "Private retreat with stunning mountain views",
    images: ["/mock/property1.jpg"],
  },
  {
    id: 4,
    title: "Beachfront Paradise",
    price: 15900000,
    bedrooms: 6,
    bathrooms: 7,
    squareFootage: 8200,
    yearBuilt: 2021,
    propertyType: "Single Family", // Changed from Estate
    status: "For Sale",
    location: "Kahala, HI",
    description: "Magnificent beachfront estate with private beach access",
    images: ["/mock/property1.jpg"],
  },
  {
    id: 5,
    title: "Tropical Garden Home",
    price: 4200000,
    bedrooms: 4,
    bathrooms: 3,
    squareFootage: 2900,
    yearBuilt: 2017,
    propertyType: "Single Family",
    status: "For Sale",
    location: "Hanalei, HI",
    description: "Charming home surrounded by lush tropical gardens",
    images: ["/mock/property1.jpg"],
  },
  {
    id: 6,
    title: "Contemporary Ocean View Condo",
    price: 3500000,
    bedrooms: 2,
    bathrooms: 2.5,
    squareFootage: 1800,
    yearBuilt: 2022,
    propertyType: "Condo",
    status: "For Sale",
    location: "Kapalua, HI",
    description: "Modern condo with stunning ocean views",
    images: ["/mock/property1.jpg"],
  }
];
